name: intelliqueue
description: "Final Year Project - Queue Management System"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking (optional for later)
  http: ^1.2.0

  # State Management & Navigation
  get: ^4.7.3

  # Responsive UI
  flutter_screenutil: ^5.9.3

  # Local Storage (session / login state)
  shared_preferences: ^2.2.2

  # SVG support
  flutter_svg: ^2.2.3

  # Google Fonts
  google_fonts: ^6.3.2

  # Local database (offline)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Password hashing
  crypto: ^3.0.3

  # App version info
  package_info_plus: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
